/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package orchestra

import org.gradle.api.Project
import org.gradle.api.Plugin

class BatsPlugin {

    static void importTasks(Project project, Plugin plugin, String dockerImageAndTag) {
        project.task('batsTest') {
            doLast {
                String script = 'bats-test.sh'

                FileUtil.copyFileFromPlugin(plugin, 'artifacts/bats.tar', "${project.buildDir}/bats.tar")
                FileUtil.runWrapperScript(project, plugin, script)
            }
        }
    }

}
