/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package orchestra

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'devops-orchestra' plugin.
 */
class OrchestraPluginTest extends Specification {

    def 'plugin registers task'() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply('devops-orchestra')

        then:
        project.tasks.findByName('dockerLint') != null
        project.tasks.findByName('dockerScan') != null
        project.tasks.findByName('dockerBuild') != null
        project.tasks.findByName('dockerTest') != null
        project.tasks.findByName('dockerPush') != null
        project.tasks.findByName('dockerEcrTagCheck') != null

        project.tasks.findByName('cfnLint') != null
        project.tasks.findByName('cfnDeploy') != null
        project.tasks.findByName('cfnValidate') != null
        project.tasks.findByName('cfnDelete') != null
        project.tasks.findByName('cfnChangeSetCreate') != null
        project.tasks.findByName('cfnChangeSetView') != null
        project.tasks.findByName('cfnChangeSetExec') != null
        project.tasks.findByName('cfnChangeSetDelete') != null

        project.tasks.findByName('helmUninstall') != null
        project.tasks.findByName('helmInstall') != null
        project.tasks.findByName('helmTest') != null
        project.tasks.findByName('helmLint') != null
        project.tasks.findByName('helmDiff') != null

        project.tasks.findByName('groovyLint') != null

        project.tasks.findByName('awsEksInit') != null
        project.tasks.findByName('awsEcrLogin') != null
        project.tasks.findByName('awsEmptyBucket') != null
        project.tasks.findByName('awsSsmToYaml') != null

        project.tasks.findByName('gitClean') != null

        project.tasks.findByName('lambdaLint') != null
        project.tasks.findByName('lambdaBuild') != null
        project.tasks.findByName('lambdaUpload') != null

        project.tasks.findByName('batsTest') != null

        project.tasks.findByName('checkTools') != null

        project.tasks.findByName('samDeploy') != null
        project.tasks.findByName('samValidate') != null
        project.tasks.findByName('samDelete') != null
        project.tasks.findByName('samChangeSet') != null

        project.tasks.findByName('ansibleCheck') != null
        project.tasks.findByName('ansiblePlaybook') != null
    }

}
